forge 'https://forgeapi.puppetlabs.com'

mod 'garethr-erlang', '0.3.0'
mod 'garethr-golang', '0.1.1'
mod 'maestrodev-maven', '1.4.0'
mod 'maestrodev-wget', '1.7.3'
mod 'puppet-nodejs', '2.3.0'
mod 'puppetlabs-apt', '1.8.0'
mod 'puppetlabs-git', '0.5.0'
mod 'puppetlabs-java', '2.1.0'
mod 'puppetlabs-stdlib', '4.17.1'
mod 'puppetlabs-vcsrepo', '1.5.0'
mod 'stahnma-epel', '1.2.2'
